org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Kotlin inkrementalno prevođenje pravi problem na Windowsu (build folder je
# na putanji sa razmakom, pa Gradle ne uspe da zatvori svoje keš fajlove).
# Bez njega build traje malo duže, ali prolazi.
kotlin.incremental=false
